# Site settings
title: getsetblog
email: getsetbro@users.noreply.github.com
author: Seth Broweleit
description: > # this means to ignore newlines until "baseurl:"
  Official blog spot of Seth Broweleit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.getsetbro.com" # the base hostname & protocol for your site
twitter_username: getsetbro
github_username:  getsetbro

# Build settings
markdown: kramdown
permalink: none
