# Site settings
title: getsetblog
email: hello@getsetbro.com
author: Seth Broweleit
description: > # this means to ignore newlines until "baseurl:"
  Official blog spot of Seth Broweleit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getsetbro.com" # the base hostname & protocol for your site
twitter_username: getsetbro
github_username:  getsetbro

# Build settings
markdown: kramdown
permalink: none
